### ISSUE TITLE
Many songs not downloading

### ISSUE THREAD

**Issue by GitStudying** [supersu-man/SpotifyPlaylistDownloader#1]
I tried downloading a playlist using the link, supplied a subfolder name, but it throws says, java.netMalformedURLException: no protocol:. And java.lang.IndexOutOfBoundsException: Index: 1, Size: 1. 

From the playlist of about 3360 songs, about 48 were downloaded correctly.
From around 1500 songs it seemed to retry the skipped songs earlier and jumps between (2-3-5-... upwards) and (1500 and up) and continued this till the playlist was completed (not fully downloaded, but tried to download all songs).

**Comment by supersu-man** [comment]
can you share me your Spotify playlist link, I'll see where it goes wrong. Because It worked with a Playlist link of 900 songs for me.

**Comment by GitStudying** [comment]
https://open.spotify.com/playlist/4oTx9r8HldEowENK1r971p?si=GWiMtEDtSU6zp1teuXNLxg, is the literal spotify share link, but if I am correct officially, https://open.spotify.com/playlist/4oTx9r8HldEowENK1r971p is enough. The app does not handle these differently as I tried both to be sure.

**Comment by supersu-man** [comment]
Found major bugs and are fixed. Released [v1.1](https://github.com/supersu-man/SpotifyPlaylistDownloader/releases/tag/v1.1). It should download all the songs on list now.
There is an issue which still exists. That is if  YouTube search results show same result for two different music because the names are almost similar, it downloads the same music file again and replaces because it thinks it's the same music file. It has to do with search results of YouTube.

Good luck downloading 3000 songs.
